version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - '8080:8080'
    volumes:
      - .:/app

  db:
    image: mysql:5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_ddd
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data: